/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchProcessRouteImport } from './routes/research-process'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBemeRouteImport } from './routes/api/beme'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPortalSiteManagementRouteImport } from './routes/_authenticated/portal.site-management'
import { Route as AuthenticatedPortalSettingsRouteImport } from './routes/_authenticated/portal.settings'
import { Route as AuthenticatedPortalOrgChartRouteImport } from './routes/_authenticated/portal.org-chart'
import { Route as AuthenticatedPortalMessagesRouteImport } from './routes/_authenticated/portal.messages'
import { Route as AuthenticatedPortalMentorRouteImport } from './routes/_authenticated/portal.mentor'
import { Route as AuthenticatedPortalMeetingsRouteImport } from './routes/_authenticated/portal.meetings'
import { Route as AuthenticatedPortalMailingListRouteImport } from './routes/_authenticated/portal.mailing-list'
import { Route as AuthenticatedPortalDirectoryRouteImport } from './routes/_authenticated/portal.directory'
import { Route as AuthenticatedPortalCoursesRouteImport } from './routes/_authenticated/portal.courses'
import { Route as AuthenticatedPortalCompleteRegistrationRouteImport } from './routes/_authenticated/portal.complete-registration'
import { Route as AuthenticatedPortalCalendarRouteImport } from './routes/_authenticated/portal.calendar'
import { Route as AuthenticatedPortalBemeRouteImport } from './routes/_authenticated/portal.beme'
import { Route as AuthenticatedPortalAnnouncementsRouteImport } from './routes/_authenticated/portal.announcements'
import { Route as AuthenticatedPortalAdmissionsRouteImport } from './routes/_authenticated/portal.admissions'
import { Route as AuthenticatedPortalAdminRouteImport } from './routes/_authenticated/portal.admin'

const ResearchProcessRoute = ResearchProcessRouteImport.update({
  id: '/research-process',
  path: '/research-process',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBemeRoute = ApiBemeRouteImport.update({
  id: '/api/beme',
  path: '/api/beme',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalSiteManagementRoute =
  AuthenticatedPortalSiteManagementRouteImport.update({
    id: '/site-management',
    path: '/site-management',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalSettingsRoute =
  AuthenticatedPortalSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalOrgChartRoute =
  AuthenticatedPortalOrgChartRouteImport.update({
    id: '/org-chart',
    path: '/org-chart',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalMessagesRoute =
  AuthenticatedPortalMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalMentorRoute =
  AuthenticatedPortalMentorRouteImport.update({
    id: '/mentor',
    path: '/mentor',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalMeetingsRoute =
  AuthenticatedPortalMeetingsRouteImport.update({
    id: '/meetings',
    path: '/meetings',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalMailingListRoute =
  AuthenticatedPortalMailingListRouteImport.update({
    id: '/mailing-list',
    path: '/mailing-list',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDirectoryRoute =
  AuthenticatedPortalDirectoryRouteImport.update({
    id: '/directory',
    path: '/directory',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalCoursesRoute =
  AuthenticatedPortalCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalCompleteRegistrationRoute =
  AuthenticatedPortalCompleteRegistrationRouteImport.update({
    id: '/complete-registration',
    path: '/complete-registration',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalCalendarRoute =
  AuthenticatedPortalCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalBemeRoute = AuthenticatedPortalBemeRouteImport.update({
  id: '/beme',
  path: '/beme',
  getParentRoute: () => AuthenticatedPortalRoute,
} as any)
const AuthenticatedPortalAnnouncementsRoute =
  AuthenticatedPortalAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAdmissionsRoute =
  AuthenticatedPortalAdmissionsRouteImport.update({
    id: '/admissions',
    path: '/admissions',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAdminRoute =
  AuthenticatedPortalAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/leadership': typeof LeadershipRoute
  '/research-process': typeof ResearchProcessRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/api/beme': typeof ApiBemeRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/portal/admissions': typeof AuthenticatedPortalAdmissionsRoute
  '/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/portal/beme': typeof AuthenticatedPortalBemeRoute
  '/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/portal/complete-registration': typeof AuthenticatedPortalCompleteRegistrationRoute
  '/portal/courses': typeof AuthenticatedPortalCoursesRoute
  '/portal/directory': typeof AuthenticatedPortalDirectoryRoute
  '/portal/mailing-list': typeof AuthenticatedPortalMailingListRoute
  '/portal/meetings': typeof AuthenticatedPortalMeetingsRoute
  '/portal/mentor': typeof AuthenticatedPortalMentorRoute
  '/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/portal/org-chart': typeof AuthenticatedPortalOrgChartRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/site-management': typeof AuthenticatedPortalSiteManagementRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/leadership': typeof LeadershipRoute
  '/research-process': typeof ResearchProcessRoute
  '/api/beme': typeof ApiBemeRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/portal/admissions': typeof AuthenticatedPortalAdmissionsRoute
  '/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/portal/beme': typeof AuthenticatedPortalBemeRoute
  '/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/portal/complete-registration': typeof AuthenticatedPortalCompleteRegistrationRoute
  '/portal/courses': typeof AuthenticatedPortalCoursesRoute
  '/portal/directory': typeof AuthenticatedPortalDirectoryRoute
  '/portal/mailing-list': typeof AuthenticatedPortalMailingListRoute
  '/portal/meetings': typeof AuthenticatedPortalMeetingsRoute
  '/portal/mentor': typeof AuthenticatedPortalMentorRoute
  '/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/portal/org-chart': typeof AuthenticatedPortalOrgChartRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/site-management': typeof AuthenticatedPortalSiteManagementRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/leadership': typeof LeadershipRoute
  '/research-process': typeof ResearchProcessRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/api/beme': typeof ApiBemeRoute
  '/_authenticated/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/_authenticated/portal/admissions': typeof AuthenticatedPortalAdmissionsRoute
  '/_authenticated/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/_authenticated/portal/beme': typeof AuthenticatedPortalBemeRoute
  '/_authenticated/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/_authenticated/portal/complete-registration': typeof AuthenticatedPortalCompleteRegistrationRoute
  '/_authenticated/portal/courses': typeof AuthenticatedPortalCoursesRoute
  '/_authenticated/portal/directory': typeof AuthenticatedPortalDirectoryRoute
  '/_authenticated/portal/mailing-list': typeof AuthenticatedPortalMailingListRoute
  '/_authenticated/portal/meetings': typeof AuthenticatedPortalMeetingsRoute
  '/_authenticated/portal/mentor': typeof AuthenticatedPortalMentorRoute
  '/_authenticated/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/_authenticated/portal/org-chart': typeof AuthenticatedPortalOrgChartRoute
  '/_authenticated/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/_authenticated/portal/site-management': typeof AuthenticatedPortalSiteManagementRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/auth'
    | '/journal'
    | '/leadership'
    | '/research-process'
    | '/portal'
    | '/api/beme'
    | '/portal/admin'
    | '/portal/admissions'
    | '/portal/announcements'
    | '/portal/beme'
    | '/portal/calendar'
    | '/portal/complete-registration'
    | '/portal/courses'
    | '/portal/directory'
    | '/portal/mailing-list'
    | '/portal/meetings'
    | '/portal/mentor'
    | '/portal/messages'
    | '/portal/org-chart'
    | '/portal/settings'
    | '/portal/site-management'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/auth'
    | '/journal'
    | '/leadership'
    | '/research-process'
    | '/api/beme'
    | '/portal/admin'
    | '/portal/admissions'
    | '/portal/announcements'
    | '/portal/beme'
    | '/portal/calendar'
    | '/portal/complete-registration'
    | '/portal/courses'
    | '/portal/directory'
    | '/portal/mailing-list'
    | '/portal/meetings'
    | '/portal/mentor'
    | '/portal/messages'
    | '/portal/org-chart'
    | '/portal/settings'
    | '/portal/site-management'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apply'
    | '/auth'
    | '/journal'
    | '/leadership'
    | '/research-process'
    | '/_authenticated/portal'
    | '/api/beme'
    | '/_authenticated/portal/admin'
    | '/_authenticated/portal/admissions'
    | '/_authenticated/portal/announcements'
    | '/_authenticated/portal/beme'
    | '/_authenticated/portal/calendar'
    | '/_authenticated/portal/complete-registration'
    | '/_authenticated/portal/courses'
    | '/_authenticated/portal/directory'
    | '/_authenticated/portal/mailing-list'
    | '/_authenticated/portal/meetings'
    | '/_authenticated/portal/mentor'
    | '/_authenticated/portal/messages'
    | '/_authenticated/portal/org-chart'
    | '/_authenticated/portal/settings'
    | '/_authenticated/portal/site-management'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  JournalRoute: typeof JournalRoute
  LeadershipRoute: typeof LeadershipRoute
  ResearchProcessRoute: typeof ResearchProcessRoute
  ApiBemeRoute: typeof ApiBemeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research-process': {
      id: '/research-process'
      path: '/research-process'
      fullPath: '/research-process'
      preLoaderRoute: typeof ResearchProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beme': {
      id: '/api/beme'
      path: '/api/beme'
      fullPath: '/api/beme'
      preLoaderRoute: typeof ApiBemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/site-management': {
      id: '/_authenticated/portal/site-management'
      path: '/site-management'
      fullPath: '/portal/site-management'
      preLoaderRoute: typeof AuthenticatedPortalSiteManagementRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/settings': {
      id: '/_authenticated/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof AuthenticatedPortalSettingsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/org-chart': {
      id: '/_authenticated/portal/org-chart'
      path: '/org-chart'
      fullPath: '/portal/org-chart'
      preLoaderRoute: typeof AuthenticatedPortalOrgChartRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/messages': {
      id: '/_authenticated/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof AuthenticatedPortalMessagesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/mentor': {
      id: '/_authenticated/portal/mentor'
      path: '/mentor'
      fullPath: '/portal/mentor'
      preLoaderRoute: typeof AuthenticatedPortalMentorRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/meetings': {
      id: '/_authenticated/portal/meetings'
      path: '/meetings'
      fullPath: '/portal/meetings'
      preLoaderRoute: typeof AuthenticatedPortalMeetingsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/mailing-list': {
      id: '/_authenticated/portal/mailing-list'
      path: '/mailing-list'
      fullPath: '/portal/mailing-list'
      preLoaderRoute: typeof AuthenticatedPortalMailingListRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/directory': {
      id: '/_authenticated/portal/directory'
      path: '/directory'
      fullPath: '/portal/directory'
      preLoaderRoute: typeof AuthenticatedPortalDirectoryRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/courses': {
      id: '/_authenticated/portal/courses'
      path: '/courses'
      fullPath: '/portal/courses'
      preLoaderRoute: typeof AuthenticatedPortalCoursesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/complete-registration': {
      id: '/_authenticated/portal/complete-registration'
      path: '/complete-registration'
      fullPath: '/portal/complete-registration'
      preLoaderRoute: typeof AuthenticatedPortalCompleteRegistrationRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/calendar': {
      id: '/_authenticated/portal/calendar'
      path: '/calendar'
      fullPath: '/portal/calendar'
      preLoaderRoute: typeof AuthenticatedPortalCalendarRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/beme': {
      id: '/_authenticated/portal/beme'
      path: '/beme'
      fullPath: '/portal/beme'
      preLoaderRoute: typeof AuthenticatedPortalBemeRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/announcements': {
      id: '/_authenticated/portal/announcements'
      path: '/announcements'
      fullPath: '/portal/announcements'
      preLoaderRoute: typeof AuthenticatedPortalAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/admissions': {
      id: '/_authenticated/portal/admissions'
      path: '/admissions'
      fullPath: '/portal/admissions'
      preLoaderRoute: typeof AuthenticatedPortalAdmissionsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/admin': {
      id: '/_authenticated/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof AuthenticatedPortalAdminRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
  }
}

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAdminRoute: typeof AuthenticatedPortalAdminRoute
  AuthenticatedPortalAdmissionsRoute: typeof AuthenticatedPortalAdmissionsRoute
  AuthenticatedPortalAnnouncementsRoute: typeof AuthenticatedPortalAnnouncementsRoute
  AuthenticatedPortalBemeRoute: typeof AuthenticatedPortalBemeRoute
  AuthenticatedPortalCalendarRoute: typeof AuthenticatedPortalCalendarRoute
  AuthenticatedPortalCompleteRegistrationRoute: typeof AuthenticatedPortalCompleteRegistrationRoute
  AuthenticatedPortalCoursesRoute: typeof AuthenticatedPortalCoursesRoute
  AuthenticatedPortalDirectoryRoute: typeof AuthenticatedPortalDirectoryRoute
  AuthenticatedPortalMailingListRoute: typeof AuthenticatedPortalMailingListRoute
  AuthenticatedPortalMeetingsRoute: typeof AuthenticatedPortalMeetingsRoute
  AuthenticatedPortalMentorRoute: typeof AuthenticatedPortalMentorRoute
  AuthenticatedPortalMessagesRoute: typeof AuthenticatedPortalMessagesRoute
  AuthenticatedPortalOrgChartRoute: typeof AuthenticatedPortalOrgChartRoute
  AuthenticatedPortalSettingsRoute: typeof AuthenticatedPortalSettingsRoute
  AuthenticatedPortalSiteManagementRoute: typeof AuthenticatedPortalSiteManagementRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAdminRoute: AuthenticatedPortalAdminRoute,
  AuthenticatedPortalAdmissionsRoute: AuthenticatedPortalAdmissionsRoute,
  AuthenticatedPortalAnnouncementsRoute: AuthenticatedPortalAnnouncementsRoute,
  AuthenticatedPortalBemeRoute: AuthenticatedPortalBemeRoute,
  AuthenticatedPortalCalendarRoute: AuthenticatedPortalCalendarRoute,
  AuthenticatedPortalCompleteRegistrationRoute:
    AuthenticatedPortalCompleteRegistrationRoute,
  AuthenticatedPortalCoursesRoute: AuthenticatedPortalCoursesRoute,
  AuthenticatedPortalDirectoryRoute: AuthenticatedPortalDirectoryRoute,
  AuthenticatedPortalMailingListRoute: AuthenticatedPortalMailingListRoute,
  AuthenticatedPortalMeetingsRoute: AuthenticatedPortalMeetingsRoute,
  AuthenticatedPortalMentorRoute: AuthenticatedPortalMentorRoute,
  AuthenticatedPortalMessagesRoute: AuthenticatedPortalMessagesRoute,
  AuthenticatedPortalOrgChartRoute: AuthenticatedPortalOrgChartRoute,
  AuthenticatedPortalSettingsRoute: AuthenticatedPortalSettingsRoute,
  AuthenticatedPortalSiteManagementRoute:
    AuthenticatedPortalSiteManagementRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  JournalRoute: JournalRoute,
  LeadershipRoute: LeadershipRoute,
  ResearchProcessRoute: ResearchProcessRoute,
  ApiBemeRoute: ApiBemeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
